import { createStitches, PropertyValue } from "@stitches/react";
import {
  crimson,
  crimsonA,
  crimsonDark,
  crimsonDarkA,
  gray,
  grayA,
  grayDark,
  grayDarkA,
} from "@radix-ui/colors";

const space = {
  0: "0px",
  1: "0.25rem",
  "1_5": "0.375rem",
  2: "0.5rem",
  "2_5": "0.625rem",
  3: "0.75rem",
  "3_5": "0.875rem",
  4: "1rem",
  5: "1.25rem",
  6: "1.5rem",
  7: "1.75rem",
  8: "2rem",
  9: "2.25rem",
  10: "2.5rem",
  11: "2.75rem",
  12: "3rem",
  14: "3.5rem",
  16: "4rem",
  20: "5rem",
  24: "6rem",
  28: "7rem",
  32: "8rem",
  36: "9rem",
  40: "10rem",
  44: "11rem",
  48: "12rem",
  52: "13rem",
  56: "14rem",
  60: "15rem",
  64: "16rem",
  72: "18rem",
  80: "20rem",
  96: "24rem",
};

const sizes = {
  none: "none",
  xs: " 20rem",
  sm: " 24rem",
  md: " 28rem",
  lg: " 32rem",
  xl: " 36rem",
  xl2: " 42rem",
  xl3: " 48rem",
  xl4: " 56rem",
  xl5: " 64rem",
  xl6: " 72rem",
  xl7: " 80rem",
  xl8: " 92rem",
  full: "100%",
};

export const {
  config,
  createTheme,
  css,
  getCssText,
  globalCss,
  styled,
  theme,
} = createStitches({
  theme: {
    colors: {
      main1: crimson.crimson1,
      main2: crimson.crimson2,
      main3: crimson.crimson3,
      main4: crimson.crimson4,
      main5: crimson.crimson5,
      main6: crimson.crimson6,
      main7: crimson.crimson7,
      main8: crimson.crimson8,
      main9: crimson.crimson9,
      main10: crimson.crimson10,
      main11: crimson.crimson11,
      main12: crimson.crimson12,

      mainA1: crimsonA.crimsonA1,
      mainA2: crimsonA.crimsonA2,
      mainA3: crimsonA.crimsonA3,
      mainA4: crimsonA.crimsonA4,
      mainA5: crimsonA.crimsonA5,
      mainA6: crimsonA.crimsonA6,
      mainA7: crimsonA.crimsonA7,
      mainA8: crimsonA.crimsonA8,
      mainA9: crimsonA.crimsonA9,
      mainA10: crimsonA.crimsonA10,
      mainA11: crimsonA.crimsonA11,
      mainA12: crimsonA.crimsonA12,

      ...gray,
      ...grayA,
    },
    space: {
      ...space,
      ...sizes,
    },
    sizes: {
      ...space,
      ...sizes,
    },
    radii: {
      sm: "0.125rem",
      md: "0.375rem",
      lg: "0.5rem",
      xl: "0.75rem",
      xl2: "1rem",
      xl3: "1.5rem",
      full: "9999px",
    },
    zIndices: {
      1: "100",
      2: "200",
      3: "300",
      4: "400",
      5: "500",
      6: "600",
      7: "700",
      8: "800",
      9: "900",
      max: "999",
    },
    fonts: {
      system: "system-ui",
    },
    fontSizes: {
      xs: "0.75rem",
      sm: "0.875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      xl2: "1.5rem",
      xl3: "1.875rem",
      xl4: "2.25rem",
      xl5: "3rem",
      xl6: "3.75rem",
      xl7: "4.5rem",
      xl8: "6rem",
      xl9: "8rem",
    },
    fontWeights: {
      thin: 100,
      extralight: 200,
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
      black: 900,
    },
  },
  utils: {
    size: (value: PropertyValue<"width">) => ({
      width: value,
      height: value,
    }),

    mx: (value: PropertyValue<"marginLeft">) => ({
      marginLeft: value,
      marginRight: value,
    }),
    my: (value: PropertyValue<"marginTop">) => ({
      marginTop: value,
      marginBottom: value,
    }),

    px: (value: PropertyValue<"paddingLeft">) => ({
      paddingLeft: value,
      paddingRight: value,
    }),
    py: (value: PropertyValue<"paddingTop">) => ({
      paddingTop: value,
      paddingBottom: value,
    }),
  },
  media: {
    xs: "(min-width: 420px)",
    sm: "(min-width: 640px)",
    md: "(min-width: 768px)",
    lg: "(min-width: 1024px)",
    xl: "(min-width: 1280px)",
    xl2: "(min-width: 1536px)",

    rm: "(prefers-reduced-motion)",

    hover: "(hover: hover)",

    dark: "(prefers-color-scheme: dark)",
    light: "(prefers-color-scheme: light)",
  },
});

// define the dark theme using the de-constructed function
export const darkTheme = createTheme({
  colors: {
    main1: crimsonDark.crimson1,
    main2: crimsonDark.crimson2,
    main3: crimsonDark.crimson3,
    main4: crimsonDark.crimson4,
    main5: crimsonDark.crimson5,
    main6: crimsonDark.crimson6,
    main7: crimsonDark.crimson7,
    main8: crimsonDark.crimson8,
    main9: crimsonDark.crimson9,
    main10: crimsonDark.crimson10,
    main11: crimsonDark.crimson11,
    main12: crimsonDark.crimson12,

    mainA1: crimsonDarkA.crimsonA1,
    mainA2: crimsonDarkA.crimsonA2,
    mainA3: crimsonDarkA.crimsonA3,
    mainA4: crimsonDarkA.crimsonA4,
    mainA5: crimsonDarkA.crimsonA5,
    mainA6: crimsonDarkA.crimsonA6,
    mainA7: crimsonDarkA.crimsonA7,
    mainA8: crimsonDarkA.crimsonA8,
    mainA9: crimsonDarkA.crimsonA9,
    mainA10: crimsonDarkA.crimsonA10,
    mainA11: crimsonDarkA.crimsonA11,
    mainA12: crimsonDarkA.crimsonA12,

    gray1: grayDark.gray1,
    gray2: grayDark.gray2,
    gray3: grayDark.gray3,
    gray4: grayDark.gray4,
    gray5: grayDark.gray5,
    gray6: grayDark.gray6,
    gray7: grayDark.gray7,
    gray8: grayDark.gray8,
    gray9: grayDark.gray9,
    gray10: grayDark.gray10,
    gray11: grayDark.gray11,
    gray12: grayDark.gray12,

    grayA1: grayDarkA.grayA1,
    grayA2: grayDarkA.grayA2,
    grayA3: grayDarkA.grayA3,
    grayA4: grayDarkA.grayA4,
    grayA5: grayDarkA.grayA5,
    grayA6: grayDarkA.grayA6,
    grayA7: grayDarkA.grayA7,
    grayA8: grayDarkA.grayA8,
    grayA9: grayDarkA.grayA9,
    grayA10: grayDarkA.grayA10,
    grayA11: grayDarkA.grayA11,
    grayA12: grayDarkA.grayA12,
  },
});

export const globalStyles = globalCss({
  body: {
    color: "$gray12",
    backgroundColor: "$gray1",
  },
});
